// <auto-generated />
using EFCore.AppLib.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.AppLib.Migrations
{
    [DbContext(typeof(CodeFirstDbContext))]
    [Migration("20211003181228_Mig0")]
    partial class Mig0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.IL", b =>
                {
                    b.Property<string>("IlKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.HasKey("IlKod");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.ILCE", b =>
                {
                    b.Property<string>("IlceKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.HasKey("IlceKod");

                    b.HasIndex("IlKod");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.MAHALLE", b =>
                {
                    b.Property<string>("MahalleKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mahalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SbbKod")
                        .HasColumnType("TEXT");

                    b.HasKey("MahalleKod");

                    b.HasIndex("SbbKod");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.SBB", b =>
                {
                    b.Property<string>("SbbKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlceKod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemtBucakBelde")
                        .HasColumnType("TEXT");

                    b.HasKey("SbbKod");

                    b.HasIndex("IlceKod");

                    b.ToTable("SemtBucakBeldeler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.ILCE", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.IL", "Il")
                        .WithMany()
                        .HasForeignKey("IlKod");

                    b.Navigation("Il");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.MAHALLE", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.SBB", "SemtBucakBelde")
                        .WithMany()
                        .HasForeignKey("SbbKod");

                    b.Navigation("SemtBucakBelde");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.SBB", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.ILCE", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceKod");

                    b.Navigation("Ilce");
                });
#pragma warning restore 612, 618
        }
    }
}
