// <auto-generated />
using EFCore.AppLib.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.AppLib.Migrations
{
    [DbContext(typeof(CodeFirstDbContext))]
    [Migration("20211004180016_Mig0")]
    partial class Mig0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.IL", b =>
                {
                    b.Property<string>("IlKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("IlKodu");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.ILCE", b =>
                {
                    b.Property<string>("IlceKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("IlceKodu");

                    b.HasIndex("IlKodu");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.MAHALLE", b =>
                {
                    b.Property<string>("MahalleKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("MahalleAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SbbKodu")
                        .HasColumnType("TEXT");

                    b.HasKey("MahalleKodu");

                    b.HasIndex("SbbKodu");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.SBB", b =>
                {
                    b.Property<string>("SbbKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlceKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemtBucakBelde")
                        .HasColumnType("TEXT");

                    b.HasKey("SbbKodu");

                    b.HasIndex("IlceKodu");

                    b.ToTable("SemtBucakBeldeler");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.ILCE", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.IL", "Il")
                        .WithMany()
                        .HasForeignKey("IlKodu");

                    b.Navigation("Il");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.MAHALLE", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.SBB", "SemtBucakBelde")
                        .WithMany()
                        .HasForeignKey("SbbKodu");

                    b.Navigation("SemtBucakBelde");
                });

            modelBuilder.Entity("EFCore.AppLib.CodeFirst.Entities.SBB", b =>
                {
                    b.HasOne("EFCore.AppLib.CodeFirst.Entities.ILCE", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceKodu");

                    b.Navigation("Ilce");
                });
#pragma warning restore 612, 618
        }
    }
}
